apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice-web-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eeozdemir/microservices-demo.git
    path: kubernetes-manifests/sock-shop/adservice
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
