name: CI Pipeline - Build and Push to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 637423621036.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build Docker Image (Using adservice Dockerfile)
        run: |
          docker build -t sock-shop-adservice -f src/adservice/Dockerfile src/adservice/

      - name: Tag Docker Image
        run: |
          docker tag sock-shop-adservice:latest 637423621036.dkr.ecr.eu-west-1.amazonaws.com/sock-shop-adservice:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 637423621036.dkr.ecr.eu-west-1.amazonaws.com/sock-shop-adservice:latest